---
functional:
  - пользователь должен иметь возможность зарегистрироваться и авторизоваться на сайте
  - пользователь должен иметь возможность создать игру с заданными параметрами
  - пользователь должен иметь возможность играть с другими игроками и с ботами
  - пользователь должен иметь возможность присоединиться к чужой игре по приглашению
  - пользователь должен иметь возможность выбрать язык программирования в игре
  - игра должна завершаться для игрока победой, поражением или ничьей при истечении времени
  - пользователь должен иметь возможность запускать проверку своего решения в игре
  - пользователь должен иметь возможность видеть написание кода соперником в реальном времени
  - у активной игры должен быть таймер в реальном времени
  - пользователь должен получать очки за завершенные игры
  - должна формироваться таблица рейтингов игроков (leaderboard) на основе полученных очков за неделю, месяц и за всё время
  - пользователь должен иметь возможность просматривать историю завершенных игр
  - пользователь должен иметь возможность просматривать свою статистику и статистику других игроков
  - пользователь должен иметь возможность писать в чат и писать личные сообщения другим игрокам
  - пользователь должен иметь возможность создавать турниры
  - пользователь должен иметь возможность присоединяться к турнирам, созданным другими игроками
  - пользователь должен иметь возможность вернуться и продолжить игру до истечения времени, если покинул страницу с текущей игрой
non-functional:
  - сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - сайт должен быть безопасным и защищать данные пользователя
  - сайт должен быть удобным на мобильном устройстве
  - сайт должен быть протестирован на совместимость с последними версиями браузеров
  - сайт должен быть способен обрабатывать большое количество трафика 
implicit:
  - на сайте должна быть возможность выбора предпочтительного языка перевода (русский/английский) в настройках для отображения функций и заданий
  - на сайте должна быть возможность создать список друзей и возможность отсылать приглашение на игру пользователям из списка
  - пользователь должен иметь возможность создать приглашение для игры по ссылке для незарегистрированного пользователя
  - у сайта должна быть адаптивная верстка
  - пользователь должен иметь возможность видеть таймер своей активной игры даже когда находится на другой странице сайта